stages:
  extract_wormhole_data:
    cmd: pixi run python scripts/extract_wormhole_data.py
    deps:
      - scripts/extract_wormhole_data.py
      - params/extract_wormhole_data.yaml
    params:
      - params/extract_wormhole_data.yaml:
          - base_url
          - data_url
          - output_dir
          - files_to_download
    outs:
      - data/01_raw/wormhole_extracts/WORMHOLE-canonical-IDs.tar.gz
      - data/01_raw/wormhole_extracts/WORMHOLE-aliases.tar.gz
      - data/01_raw/wormhole_extracts/PANTHER-LDO-ortholog-pairs.tar.gz
      - data/01_raw/wormhole_extracts/WHRefOGs.tar.gz
      - data/01_raw/wormhole_extracts/WORMHOLE-ortholog-pairs.tar.gz
    metrics:
      - data/01_raw/wormhole_extracts/download_log.json

  extract_coxpresdb_data:
    cmd: pixi run python scripts/extract_coxpresdb_data.py
    deps:
      - scripts/extract_coxpresdb_data.py
      - params/extract_coxpresdb_data.yaml
    params:
      - params/extract_coxpresdb_data.yaml:
          - base_url
          - output_dir
          - files_to_download
    outs:
      - data/01_raw/coxpresdb_extracts/

  transform_coxpresdb_data:
    cmd: pixi run python scripts/transform_coxpresdb_data.py
    deps:
      - scripts/transform_coxpresdb_data.py
      - params/transform_coxpresdb_data.yaml
      - data/01_raw/coxpresdb_extracts/
    params:
      - params/transform_coxpresdb_data.yaml:
          - input_dir
          - output_dir
          - compression
    outs:
      - data/02_transformed/coxpresdb/
    metrics:
      - data/02_transformed/transform_log.json:
          cache: false
